// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyBcS6a1CHmGG3GuCYgYOn0vvTrtp9uZE',
    appId: '1:438952406708:web:f7ffbd70290a76b58db1e1',
    messagingSenderId: '438952406708',
    projectId: 'rotiku-9dd78',
    authDomain: 'rotiku-9dd78.firebaseapp.com',
    databaseURL: 'https://rotiku-9dd78-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rotiku-9dd78.firebasestorage.app',
    measurementId: 'G-XXZBVZHK44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMm1V1w5jw3oKJLSsypmJvcWZ3-hm86E0',
    appId: '1:438952406708:android:7d7080cce8c54ba28db1e1',
    messagingSenderId: '438952406708',
    projectId: 'rotiku-9dd78',
    databaseURL: 'https://rotiku-9dd78-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rotiku-9dd78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2PaHpKnViMajDUMg177bKZ8C03xf34uM',
    appId: '1:438952406708:ios:ded2185349818b308db1e1',
    messagingSenderId: '438952406708',
    projectId: 'rotiku-9dd78',
    databaseURL: 'https://rotiku-9dd78-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rotiku-9dd78.firebasestorage.app',
    iosBundleId: 'com.example.rotiku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2PaHpKnViMajDUMg177bKZ8C03xf34uM',
    appId: '1:438952406708:ios:ded2185349818b308db1e1',
    messagingSenderId: '438952406708',
    projectId: 'rotiku-9dd78',
    databaseURL: 'https://rotiku-9dd78-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rotiku-9dd78.firebasestorage.app',
    iosBundleId: 'com.example.rotiku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyBcS6a1CHmGG3GuCYgYOn0vvTrtp9uZE',
    appId: '1:438952406708:web:2072f438cc6b18708db1e1',
    messagingSenderId: '438952406708',
    projectId: 'rotiku-9dd78',
    authDomain: 'rotiku-9dd78.firebaseapp.com',
    databaseURL: 'https://rotiku-9dd78-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rotiku-9dd78.firebasestorage.app',
    measurementId: 'G-YMVKEZ8K8W',
  );

}